# Generated by Django 3.0.9 on 2020-08-06 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendancemof', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffdetail',
            name='attendances',
        ),
        migrations.AddField(
            model_name='attendance',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendancemof.StaffDetail'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
