# Generated by Django 3.0.9 on 2020-08-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendancemof', '0002_auto_20200806_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffdetail',
            old_name='divison',
            new_name='division',
        ),
    ]
