# Generated by Django 3.0.9 on 2020-08-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendancemof', '0003_auto_20200806_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(),
        ),
    ]
