# Generated by Django 3.0.9 on 2020-08-03 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendancemof", "0005_auto_20200730_2258"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreasuryPurposes",
            fields=[
                (
                    "attendancet20_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="attendancemof.AttendanceT20",
                    ),
                ),
                (
                    "t_id",
                    models.AutoField(default="1", primary_key=True, serialize=False),
                ),
                ("Time_Out", models.TimeField(null=True)),
                ("Late_hours", models.TimeField(null=True)),
                ("Overtime_In", models.TimeField(null=True)),
                ("Overtime_Out", models.TimeField(null=True)),
                ("Deduction_Hours", models.TimeField(null=True)),
            ],
            bases=("attendancemof.attendancet20",),
        ),
        migrations.AlterField(
            model_name="attendancet20",
            name="AttendanceDate",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="attendancet20",
            name="Time_In",
            field=models.TimeField(null=True),
        ),
        migrations.DeleteModel(name="treasury_purposes",),
    ]
